service: auction-system-notification

frameworkVersion: "2.72.4"

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev
  profile: default
  region: 'us-west-1'
  iam:
   role:
     statements:
       - Effect: Allow
         Action:
           - ses:*
         Resource: arn:aws:ses:*
       - Effect: Allow
         Action:
           - sqs:ReceiveMessage
         Resource: arn:aws:ses:*      

functions:
  sendMail:
    handler: handlers/sendMail.handler
    events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:842557994378:auction-system
        batchSize: 1
        
resources:
 Resources:
    MailQueue:
      Type: AWS::SQS::Queue
    # Properties:
    #   QueueName: MailQueue-dev
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

custom:
  bundle:
    linting: false