service: auction-auth-poc

frameworkVersion: "2.72.4"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev
  profile: default
  region: 'us-west-1'
  iam:
   role:
     statements:
       - Effect: Allow
         Action:
           - dynamodb:*
         Resource: arn:aws:dynamodb:us-west-1:842557994378:table/UsersTable
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  register:
    handler: handlers/register.handler
    events:
      - http:
          method: POST
          path: /register
  login:
    handler: handlers/login.handler
    events:
      - http:
          method: POST
          path: /login
  getUsers:
      handler: handlers/getUsers.handler
      events:
        - http:
            method: GET
            path: /get_users
  getUserById:
    handler: handlers/getUserById.handler
    events:
      - http:
          method: GET
          path: /users_by_id/{id}
          
custom:
  bundle:
    linting: false